services:
  drupal-quickstart-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./app:/var/www/html
    depends_on:
      - drupal-quickstart-db
  drupal-quickstart-db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - drupal-quickstart-db:/var/lib/mysql
volumes:
  drupal-quickstart-db:
